### ISSUE TITLE
Scenár: kombinovaný šport sa rozdelí na 2 komb. / 1 komb. a 1 obyč.

### ISSUE THREAD

**Issue by Ashen-MG** [TIS2021-FMFI/zaujem-o-sport#10]
Každý si skúsi následujúci scenár, či nie je v spore s tým návrhom, ktorý sme navrhli v jamboarde.
Link na prebiehajúci návrh ERD (jamboard):
https://jamboard.google.com/d/1z5ZEr1Tvm9datcRVMrMJQWSZ6K-MBJd3mYDsaaWl2MM/

**Comment by Sabka** [comment]
toto povazujem len za kombinaciu ostatnych dvoch pripadov. Najprv rozdelime na jednotlive a potom niektore spojime do komb. Aj tak sa to zrejme bude od uzivatela robit presne po takychto krokoch

**Comment by Ashen-MG** [comment]
@Sabka Súhlasím resp. premýšľam nad tým rovnako - zadefinovanie si 'atomických' operácií v podobe scenárov ako 'komb. šport sa rozdelí na jednotlivé' a 'dva športy sa spoja' atď. pomôže nielen návrhu, ale aj implementácií.
