### ISSUE TITLE
Návrh modelu DB

### ISSUE THREAD

**Issue by Sabka** [TIS2021-FMFI/zaujem-o-sport#11]

**Comment by Sabka** [comment]
DB mozeme navrhovat pomocou online nastroja: https://online.visual-paradigm.com/

**Comment by Sabka** [comment]
[Untitled Diagram.vpd.pdf](https://github.com/TIS2021-FMFI/zaujem-o-sport/files/7459562/Untitled.Diagram.vpd.pdf)

- toto je moj navrh, mozeme sa o nom porozpravat na zajtrajsom stretku
- rozhodla som sa to robit co najjednoduchsie, aby boli data co najprehladnejsie za cenu komplikovanejsich vypoctov na backende, tento navrh mozno bude viest k nejakemu zrkadleniu DB do triednej struktury na backende, mali by sme sa rozhodnut, ci je to to co chceme

**Comment by Ashen-MG** [comment]
Pridajme tabuľku interconnection_types:
id | name
1  | economical
2  | uneconomical
3  | total

Premenujme Donations na Founding

**Comment by Sabka** [comment]
[Untitled Diagram(1).pdf](https://github.com/TIS2021-FMFI/zaujem-o-sport/files/7468395/Untitled.Diagram.1.pdf)
Pridanie Type a premenovanie

**Comment by Sabka** [comment]
[popis k DB.pdf](https://github.com/TIS2021-FMFI/zaujem-o-sport/files/7468507/popis.k.DB.pdf)

Tak slubeny popis ktory som pisala k DB, vacsina veci bola spomenutych na stretku, ale prosim skontrolujte, ci uvazujem o tych jednotlivych dopytoch dobre a dajte vediet v komente :) dakujem

**Comment by Sabka** [comment]
[DBnavrh.vpd.pdf](https://github.com/TIS2021-FMFI/zaujem-o-sport/files/7504780/DBnavrh.vpd.pdf)


este som do DB modelu pridala tabulku s ukladanim userov a parametrov

**Comment by misovsky3** [comment]
![navrhdatabazypodlaSQL](https://user-images.githubusercontent.com/79416440/143690988-8e9146c5-7d2c-4b51-befc-4840a03eb3e6.jpg)

**Comment by Sabka** [comment]
ISuccess value -> order
