### ISSUE TITLE
Database queries issues

### ISSUE THREAD

**Issue by Ashen-MG** [TIS2021-FMFI/zaujem-o-sport#110]
Našiel problém, ktorý môže súvisieť s tým, prečo občas vyhodí, že je pool preťažený.
Ak nastane databázová chyba, nikdy nepríde `self._releaseConnection(dbConn)` a to môže mať nežiadúci efekt.
Riešenie je `self._releaseConnection(dbConn)` dať do finally bloku.

**Comment by Sabka** [comment]
@Ashen-MG neviem si predstavit ako to pridat do finally bloku, kedze dbConn je lokalna premenna v try bloku, vo finally bloku ju uz nepozna :( 

okrem toho, pretazenie sa ukazovalo vtedy, ked vsetky queries behali vpohode, bez erroru

**Comment by Sabka** [comment]
a teda nie som si ista, ci aj v tomto pripade to dokaze with blok vyriesit, ale on by mal zabezpecovat ze sa vsetko zrusi ak sa z neho vyhodi vynimka, nie ?

**Comment by Sabka** [comment]
ale pre istotu pridavam ukoncenie db spojenia na miesta kde sa raisuje vynimka

**Comment by Ashen-MG** [comment]
Vo finally by mal poznať všetky premenné, ktoré vznikli v try bloku a keďže <code>with ... as nieco</code> vlastne definuje aj premennú nieco, vo finally sa dá zavolať <code>self._releaseConnection(dbConn)</code>
@Sabka

**Comment by Sabka** [comment]
wow, tak vcera ked som to tam doplnila, tak s tym mal pycharm problem, ze nepozna tu referenciu a teraz ked to skusam, tak nekrici

**Comment by Sabka** [comment]
okay, tak uz som prisla na to, co to bol vcera za problem... ja som defaultne releasovala conn v try bloku a v momente ako som to pridala do finally, tak v pripade uspechu sa to chcelo releasnut dvakrat, to ale vyhodilo error...

aktualne je urobeny PR, kde je to vyriesene
