### ISSUE TITLE
Návrh GUI

### ISSUE THREAD

**Issue by Sabka** [TIS2021-FMFI/zaujem-o-sport#12]

**Comment by yonkel** [comment]
![Sekretarsky GUI](https://user-images.githubusercontent.com/79480591/139591142-6774f3a2-91ff-4a5f-a642-51a813416d57.png)



urobil som zatial len hruby navrh, pre 3.2.2.1 sa mi paci asi spodna moznost,  pri krajine to Q je lupa kde moze sekretarka zadat nazov

pri 3.2.2.4 tie "..." znamenaju dalsie atributy 

na stretnuti mozeme prediskutovat ci je lepsie tlacidlo spat / alebo nejake "menu" na okraji / aj aj 

ps: je to trosku docarbane lebo babka nema gumu :( ak by nieco nebolo jasne piste

**Comment by Sabka** [comment]
vyzerá to pekne :) ešte si to prejdeme zajtra na stretku

**Comment by Ashen-MG** [comment]
[tis_admin_interface_paper_wireframe.pdf](https://github.com/TIS2021-FMFI/zaujem-o-sport/files/7464303/tis_admin_interface_paper_wireframe.pdf)

**Comment by misovsky3** [comment]
[NavrchPouzivatelskehoRozhrania.pdf](https://github.com/TIS2021-FMFI/zaujem-o-sport/files/7466404/NavrchPouzivatelskehoRozhrania.pdf)

**Comment by misovsky3** [comment]
Rozpočty nebudu v eurách , ale v lokálnej mene

**Comment by Sabka** [comment]
@misovsky3  premenuj prosim poradie na uspesnost...

**Comment by misovsky3** [comment]
[Ticket Selling System.pdf](https://github.com/TIS2021-FMFI/zaujem-o-sport/files/7507598/Ticket.Selling.System.pdf)

**Comment by misovsky3** [comment]
[NavrchPouzivatelskehoRozhrania.pdf](https://github.com/TIS2021-FMFI/zaujem-o-sport/files/7511194/GUI.pdf)

**Comment by yonkel** [comment]
zapracovanie zmien v sekretarskom interface

[secretary_interface_updated.pdf](https://github.com/TIS2021-FMFI/zaujem-o-sport/files/7531097/secretary_interface_updated.pdf)

**Comment by misovsky3** [comment]
[NavrhPouzivatelskeho.pdf](https://github.com/TIS2021-FMFI/zaujem-o-sport/files/7532299/NavrhPouzivatelskeho.pdf)
