### ISSUE TITLE
UML component diagram

### ISSUE THREAD

**Issue by Sabka** [TIS2021-FMFI/zaujem-o-sport#13]

**Comment by misovsky3** [comment]
[component diagram.pdf](https://github.com/TIS2021-FMFI/zaujem-o-sport/files/7511188/component.diagram.pdf)

**Comment by misovsky3** [comment]
1. opacna sipka pri sport - branch
2. este modul na prepocty
3. viac komponentov z hladiska funkcionality
4. tvori branch sam komponent?
5. zapisat cvs vstupy ako komponent

**Comment by misovsky3** [comment]
![Untitled](https://user-images.githubusercontent.com/79416440/141503377-713fbada-f9f8-4e07-bbab-b3a12775283a.png)
component diagram z modulov

**Comment by Sabka** [comment]
za mna fajn -> vyzera to ze to pekne vystihuje rozdelenie na moduly :)
