### ISSUE TITLE
 UML class diagram

### ISSUE THREAD

**Issue by Sabka** [TIS2021-FMFI/zaujem-o-sport#14]

**Comment by yonkel** [comment]
[ClassDiagram.pdf](https://github.com/TIS2021-FMFI/zaujem-o-sport/files/7512037/ClassDiagram.pdf)

**Comment by yonkel** [comment]
[Class Diagram v2.pdf](https://github.com/TIS2021-FMFI/zaujem-o-sport/files/7531089/Class.Diagram.v2.pdf)

**Comment by Sabka** [comment]
za mna - fajn diagram

**Comment by yonkel** [comment]
[class_backend_v3.pdf](https://github.com/TIS2021-FMFI/zaujem-o-sport/files/7632647/class_backend_v3.pdf)
