### ISSUE TITLE
user - chybajuce funkcionality

### ISSUE THREAD

**Issue by Sabka** [TIS2021-FMFI/zaujem-o-sport#140]
v poziadavkach mame : 

- Na každej stránke sa nachádza rovnaké navigačné menu s rozdielom označenia (zvýraznenia) aktívneho linku. @misovsky3 toto by mohlo byt lahke nacsskovat, stihnes to dnes ?

- Každá stránka so zobrazením resp. vizualizáciou dát obsahuje zdroj dát (text/link) na zdroj odkiaľ dané dáta pochádzajú. @misovsky3  toto som pozerala, mozno by sa to dalo dat do toho i -> informacie

- Každá stránka s nejakou tabuľkou dát načítava tabuľku a dáta v nej lazy loadingom i.e. nové dáta sa načítajú po tom, ako sa používateľ ocitne na spodku stránky resp. tabuľky. Ak už sa načítalo všetko, ukáže sa text s patričnou informáciou. @misovsky3  na toto kasleme ? dat nie je az tak vela a aj tak query vrati vsetko...

**Comment by misovsky3** [comment]
opravim to podla tych prvých dvoch bodov a ked vyjde cas mozem aj podla tretieho....ale vzdy je riadkov tolko kolko je krajin alebo sportov ,co nie je az tak vela ci?

**Comment by Sabka** [comment]
hej, tie prve dva  su dolezitejsie, ten treti asi nemusi nutne byt ....
