### ISSUE TITLE
Datovy model

### ISSUE THREAD

**Issue by yonkel** [TIS2021-FMFI/zaujem-o-sport#146]
aktualizacia datoveho modelu v navrhu ( pridanie novo vzniknutych tabuliek, popis k nim )

**Comment by Sabka** [comment]
![Untitled](https://user-images.githubusercontent.com/26357169/152788716-e91d5efa-779a-4d37-bdb2-b7cb518303aa.png)

zgenerovane z aktualnej DB

**Comment by Sabka** [comment]
opis novovzniknutých tabuliek :
- bgs - vypracovené celosvetové poradie športov, ktoré sa používa vo výpočtoch

- max points in sport - parameter potrebný na výpočty = počet bodov prvého štátu v rebríčku daného športu, pri parsovaní úspešnosti športov sa berú do úvahy len aktívne krajiny. Najviac bodov môže mať ale neaktívna krajina, teda sa tento záznam nevyskytne v tabuľke success, teda ho treba uložiť v tejto tabuľke.

- num in  sport - parameter potrebný na výpočty = počet krajín hodnotených v danom športe v success dátach. Opäť sa to nedá jednoduchým spočítaním, lebo by sa zanedbali neaktívne krajiny.

- country best order - najlepšie umiestnenie krajiny v nejakom športe

- total country points - súčet bodov krajiny vo všetkých športoch
