### ISSUE TITLE
UML state alebo UML sequence 

### ISSUE THREAD

**Issue by Sabka** [TIS2021-FMFI/zaujem-o-sport#15]

**Comment by Ashen-MG** [comment]
[sequence_diagram.pdf](https://github.com/TIS2021-FMFI/zaujem-o-sport/files/7506527/sequence_diagram.pdf)

Rozhodol som sa pre sekvenčný diagram.
Diagram popisuje (abstraktne) komunikáciu v celej aplikácií i.e. ako bude presne prebiehať akýkoľvek call od používateľa - browsera.
Prišlo mi to najvhodnejšie, keďže sa v ňom ukazuje, aký prístup oproti klasickému 'call na server - server vracia html stránku' použijeme my. 
Zároveň som sa ale snažil neísť až príliš moc do veľkých detailov/abstraktnosti ako e.g. po vrstvu TCP/IP, HTTP, ...

**Comment by Sabka** [comment]
diagram vyzera za mna super :)
