### ISSUE TITLE
Rozdelenie na moduly a návrh interfejsov

### ISSUE THREAD

**Issue by Sabka** [TIS2021-FMFI/zaujem-o-sport#16]

**Comment by Sabka** [comment]
[moduly.pdf](https://github.com/TIS2021-FMFI/zaujem-o-sport/files/7490445/moduly.pdf)

Rozdelila som projekt na moduly, poprosim vas o vyjadrenie.

**Comment by Ashen-MG** [comment]
@Sabka 
User management modul z pohľadu frontendu:
V reacte sú zaužívané tzv. adaptéry (+-naming convention), ktoré sú oddelené od komponentov, kde sa špecificky definuje všetka komunikácia s backendovým API, čiže včetne aj tých, ktoré slúžia na verifikáciu.

**Comment by Sabka** [comment]
[moduly2.pdf](https://github.com/TIS2021-FMFI/zaujem-o-sport/files/7512033/moduly2.pdf)


Zapracovanie komentaru

**Comment by Sabka** [comment]
pridat univerzalny backendovy modul ktory komunikuje s frontendovym

**Comment by Sabka** [comment]
[moduly3.pdf](https://github.com/TIS2021-FMFI/zaujem-o-sport/files/7514111/moduly3.pdf)
Zapracovana pripomienka od PP - komunikacny modul na backende
