### ISSUE TITLE
Materiál na preštudovanie

### ISSUE THREAD

**Issue by Ashen-MG** [TIS2021-FMFI/zaujem-o-sport#19]
@Sabka @misovsky3 @yonkel 
Odporúčam si zbežne naštudovať 'Main concepts' z oficiálnej reactovej dokumentácie:
https://reactjs.org/docs/hello-world.html
(podstatné a veľmi intuitívne - introduction to JSX, components and props, nový koncept, ktorému by som venoval viacej času - State and Lifecycle - ukazujú to v oop z čoho sa dá veľmi pekne potom pochopiť aj funkcionálna verzia).

a Hooks:
https://reactjs.org/docs/hooks-intro.html
Najviac budeme využívať useState() a
useEffect()  - https://reactjs.org/docs/hooks-effect.html

Ak má niekto radšej video tutoriály:
https://www.youtube.com/watch?v=j942wKiXFu8&list=PL4cUxeGkcC9gZD-Tvwfod2gaISzfRiP9d
Síce veľmi kvalitne spracované videá, môže to byť dosť na začiatok.

Skvelý tutorial na jednoduchý projekt vo Flasku, ktorý budeme používať na backende:
https://www.digitalocean.com/community/tutorials/how-to-make-a-web-application-using-flask-in-python-3
Stačí mať nainštalovaný python a flask (pip install flask / pip3 install flask (častejší prípad na linuxe)). Ukazujú zároveň prácu vo virtuálnom pythonovom prostredí (podobnú vec sme robili na mat. analýze s condou v rámci labu).

Z typescriptu sa hodí si primárne pozrieť moduly:
https://www.typescriptlang.org/docs/handbook/modules.html

**Comment by Sabka** [comment]
@Ashen-MG  este mozno nejake odporucanie, ake IDEcko pouzivat ?

**Comment by Ashen-MG** [comment]
Aby to tu teda zostalo:
Za mňa vytunený sublime text s pluginmi na React a pod.
alebo Jetbrains produkty:
Pycharm na backend/db
Webstorm na frontend (priama podpora typescriptu a Reactu)
Veľa ľudí ešte používa visual studio code - ja ho osobne nemusím (avšak je odosť menej náročný na ramku oproti webstormu)
