### ISSUE TITLE
Spísanie  katalógu požiadaviek.

### ISSUE THREAD

**Issue by Sabka** [TIS2021-FMFI/zaujem-o-sport#2]
Pracujeme tu : https://docs.google.com/document/d/1_MJ5uVrcsse4wmyUYT6ZvvzTqn1saPIQ7DJDduUUQCE/edit

**Comment by Ashen-MG** [comment]
@Sabka Dopísané subkapitoly 2.2 a 2.3

**Comment by pavelpetrovic** [comment]
vypadlo z KP, lebo patri do navrhu:

Backend - API

Sprostredkovanie zabezpečenej komunikácie medzi používateľom (všetkých typov) - frontend-om, databázou a serverom.
Navrhnutie API podľa REST API architektúry.
Dokumentácia k jednotlivým trasam (routes).
Návrh a implementácia dátových štruktúr pre prácu s databázou.

Štruktúra databázy

Vymyslieť štruktúru, ktorá bude popisovať športy, disciplíny a kombinované športy.
Importovať dáta od zadávateľa.
Vytvoriť tabuľku používateľov s emailom a bezpečne uloženým heslom a kategóriou používateľa = sekretárka / admin.
V databáze sú uložené všetky svetové krajiny (a jedna špeciálna - BIGGESTGLOBALSPORTS), no len niektoré sú označené ako aktívne.


Spracovanie vstupných dát

Vytvoriť funkciu, ktorá dostane kód športu, názov športu a disciplínu a overí, či údaje sedia s tými v DB, vráti informácie o chybách ktoré našla.
Vytvoriť funkciu ktorá sparsuje a overí správnosť a vráti zoznam prípadných chýb pomocou 3.1.1 dát typu 1, t.j. csv ktorého jeden riadok je vo formáte:
kód športu
názov športu
názov kategórie športu
suma (peňazí)
ďalšie prípadné informácie po týchto odignoruje
Vytvoriť funkciu ktorá sparsuje dáta typu 2, t.j. excelovský súbor, ktorý obsahuje poradie krajín k športu.
Vytvoriť funkciu ktorá sparsuje dáta typu 3, t.j. matica v exceli.
(versioning databázy) Vytvoriť funkciu ktorá urobí zálohu celej DB a uloží ju (dump) (ako názov použije aktuálny dátum a čas).
Výsledok úspešného parsovania resp. úspešného editu po parsovaní neostáva v pamäti, ale ukladá sa v databáze.

**Comment by Sabka** [comment]
[Katalóg požiadaviek.pdf](https://github.com/TIS2021-FMFI/zaujem-o-sport/files/7538865/Katalog.poziadaviek.pdf)

Finálna verzia schválená PP aj zadávateľom.
