### ISSUE TITLE
Testovacie scenáre

### ISSUE THREAD

**Issue by Sabka** [TIS2021-FMFI/zaujem-o-sport#20]

**Comment by Sabka** [comment]
Budeme mať týchto 13. scenárov, ktoré pokryjú všetky požiadavky v KP: 

1. Scenár - Zobrazenie úvodnej stránky pre bežného používateľa a pohyb v navigačnom menu a jednotlivých zobrazenie stránok s dátami (3.1.1, 3.1.2, 3.1.3, 3.1.5, 3.1.6)
2. Scenár - Stránka s rebríčkom so zapnutým GPS (3.1.4)
3. Scenár - Stránka s rebríčkom s vypnutým GPS (3.1.4)
4. Scenár - Prihlásenie do sekretárskeho interface a zobrazenie úvodnej stránky a vertikálnej navigácie (3.2.1, 3.2.2.1)
5. Scenár - Prihlásenie do administrátorského interface a zobrazenie úvodnej stránky a vertikálnej navigácie (3.3.1, 3.3.2.1)
6. Scenár - Sekretárka nahrá dáta typu 1 (3.2.2.2, 3.2.2.3, 3.2.2.4, 3.2.3)
7. Scenár - Sekretárka pridáva šport / odvetvie (3.2.2.5, 3.2.2.6)
8. Scenár - Sekretárka si prezerá kódy krajín / športov (3.2.4, 3.2.5)
9. Scenár - Admin nahráva dáta typu 1, 2, 3 (3.3.2.2, 3.3.2.9)
10. Scenár - Admin upravuje kód športu (3.3.2.3, 3.3.2.8, 3.3.2.9)
11. Scenár - Admin pridáva šport, odvetvie, krajinu (3.3.2.4, 3.3.2.5, 3.3.2.6, 3.3.2.7, 3.3.2.8, 3.3.2.9)
12. Scenár - Admin si prezerá kódy krajín / športov (3.3.3)
13. Scenár - Kontrola zálohovania dát (3.4)

**Comment by Ashen-MG** [comment]
(Scenár 1)
Používateľ príde na hlavnú stránku. Na vrchu stránky sa nachádza navigačné menu s možnosťami - linkami (prepojenie krajín, rozpočty krajín, úspešnosť v športoch, export, rebríček), ktorými sa pohybuje po jednotlivých stránkach.
Na každej stránke sa nachádza rovnaké navigačné menu s rozdielom označenia (zvýraznenia) aktívneho linku.
Každá stránka so zobrazením resp. vizualizáciou dát obsahuje zdroj dát (text/link) na zdroj odkiaľ dané dáta pochádzajú.
Každá stránka s nejakou tabuľkou dát načítava tabuľku a dáta v nej lazy loadingom i.e. nové dáta sa načítajú po tom, ako sa používateľ ocitne na spodku stránky resp. tabuľky. Ak už sa načítalo všetko, ukáže sa text s patričnou informáciou.
Každá stránka sa dá načítať bez klikania na linky s navigačného menu priamym načítaním vhodnej url adresy danej stránky.

Prvotná načítaná stránka je stránka so zobrazením prepojenia krajín, na ktorú sa dá taktiež dostať kliknutím na link 'prepojenie krajín' v navigačnom menu.
Na stránke sa nachádza dropdown s možnosťou výberu druhu prepojenia (kliknutím sa zobrazia možnosti: ekonomické, neekonomické, celkové), switch výberu zobrazenia (mapa, tabuľa/zoznam) a dropdown s možnosťou výberu krajiny (kliknutím sa zobrazia na výber všetky krajiny).
Po výbere prepojenia a zobrazenia sa podľa výberu zobrazenia ukáže mapa s číselnými hodnotami alebo tabuľka s krajinami a ich váhami, ktoré hovoria, akú vysokú previazanosť má krajina na mape vzhľadom na zvolenú krajinu a druh prepojenia.
Po mape sa dá kliknutím, ťahaním kurzora príp. klávesovými skratkami pohybovať a približovať.

Kliknutím na link 'rozpočty krajín' v navigačnom menu sa dynamicky načíta stránka, na ktorej je dropdown s možnosťou výberu krajiny (kliknutím sa zobrazia na výber všetky krajiny). Po výbere krajiny sa načíta tabuľka so stĺpcami: názov športu, názov odvetvia, údaj o tom, či je kombinovaný, suma (peňazí) v lokálnej mene danej krajiny. Explicitne sa aj na stránke zobrazuje nie len zdroj dát, ale aj kód a názov použitej meny.

Kliknutím na link 'úspešnosť v športoch ' v navigačnom menu sa dynamicky načíta stránka, na ktorej je dropdown s možnosťou výberu športu (kliknutím sa zobrazia na výber všetky športy uložené v databáze). Po výbere športu sa zobrazí tabuľka poradí krajín podľa počtu bodov získaných v danom športe.

Kliknutím na link 'export ' v navigačnom menu sa dynamicky načíta stránka, na ktorej je dropdown s možnosťou výberu verzie (kliknutím sa zobrazia na výber všetky uchovávané dostupné verzie dát) a tlačidlo 'Stiahnutie exportu'. Po kliknutí na tlačidlo sa začnú automaticky dáta sťahovať.

(Scenár 2)
Kliknutím na link 'rebríček' v navigačnom menu sa dynamicky načíta stránka. Na používateľa vyskočí okno - žiadosť o detekciu polohy. Používateľ ju povolí a používa zariadenie s GPS - teda detekcia polohy bude úspešná. Na stránke sa po ľavej strane zobrazuje globálne poradie športov - tabuľka s poradovým číslom, názvom športu a obrázkom. Po pravej strane sa nachádza rovnako štruktúrovaná tabuľka ako pre globálne poradie športov pre Slovensko.

(Scenár 3)
Kliknutím na link 'rebríček' v navigačnom menu sa dynamicky načíta stránka. Na používateľa vyskočí okno - žiadosť o detekciu polohy. Používateľ ju zamietne alebo používa zariadenie bez GPS - teda detekcia polohy bude neúspešná. Na stránke sa po ľavej strane zobrazuje globálne poradie športov - tabuľka s poradovým číslom, názvom športu a obrázkom. Po pravej strane sa nachádza rovnako štruktúrovaná tabuľka ako pre globálne poradie športov pre lokalizovanú krajinu s GPS polohy používateľa.

**Comment by Ashen-MG** [comment]
Na našom hovore dodám nejaké detaily resp. doladíme niektoré časti, u ktorých je viacero možností.

**Comment by Sabka** [comment]
@Ashen-MG  este to prosim ta nakopiruj aj do docu: https://docs.google.com/document/d/1ZfItuKcPEc_JU-ByIJUYSOyfQB-BHH0UUC-MoFOvkh4/edit

**Comment by Sabka** [comment]
[Testovacie scenare.pdf](https://github.com/TIS2021-FMFI/zaujem-o-sport/files/7595160/Testovacie.scenare.pdf)
