### ISSUE TITLE
Prvotné spustenie aplikácie

### ISSUE THREAD

**Issue by Ashen-MG** [TIS2021-FMFI/zaujem-o-sport#23]
Vytvoril som base projekt od ktorého sa budeme môcť odraziť ďalej.
Pridal som aj potrebné README súbory pre správne sprovoznenie na vašom lokálnom pc. 
Skúste si to do nášho budúceho stretnutia nech môžeme vyriešiť prípadné problémy.
Všetko je zatiaľ v branchi base. 
Podarilo sa mi mimo bootstrapu 5 zohnať aj pekné ikony (keď si sprovozníte frontend, tak na / route ich budete mimo iného vidieť).
Každopádne pokojne píšte na tento issue v prípade akýchkoľvek problém - najlepšie, ak pošlete screenshot, konzolový výpis, výpis z logu, ...

**Comment by Sabka** [comment]
@yonkel ked sa to podari aj tebe, napis do issue a mozes zatvorit :)
