### ISSUE TITLE
create a generate script

### ISSUE THREAD

**Issue by Sabka** [TIS2021-FMFI/zaujem-o-sport#24]

**Comment by misovsky3** [comment]
Prvá verzia create scriptu bez constraints
[create_script.txt](https://github.com/TIS2021-FMFI/zaujem-o-sport/files/7612143/create_script.txt)

**Comment by Sabka** [comment]
Za mna to vyzera ok :)

**Comment by misovsky3** [comment]
[create_script.txt](https://github.com/TIS2021-FMFI/zaujem-o-sport/files/7613394/create_script.txt)

**Comment by yonkel** [comment]
[gen_success.txt](https://github.com/TIS2021-FMFI/zaujem-o-sport/files/7675500/gen_success.txt)

**Comment by yonkel** [comment]
[gen_script.txt](https://github.com/TIS2021-FMFI/zaujem-o-sport/files/7717767/gen_script.txt) v2

**Comment by yonkel** [comment]
[gen.zip](https://github.com/TIS2021-FMFI/zaujem-o-sport/files/7741842/gen.zip)
[gen_script.txt](https://github.com/TIS2021-FMFI/zaujem-o-sport/files/7741841/gen_script.txt)

**Comment by Sabka** [comment]
@yonkel prosim ta prerob tie country code na trojpismenove kody, tu som nasla zdroj dat :https://github.com/lukes/ISO-3166-Countries-with-Regional-Codes/blob/master/all/all.csv

**Comment by Sabka** [comment]
@yonkel  tie interconnectness types mas nespravne, lebo tam maju byt tie import, export, language... a z tych sa potom vypocita ta ekonomicka, neekonomicka a celkova previazanost... 

potom teda bude treba prerobit aj insert do interconnectness

**Comment by Sabka** [comment]
Update create scriptu -> ku krajine som pridala flag is_active, aby sme z neaktivnych mohli ponukat pri pridavani krajiny a automaticky mali k dispozicii kody existujucich krajin, teda ich nemusi sekretarka/admin vymyslat


[create_script.txt](https://github.com/TIS2021-FMFI/zaujem-o-sport/files/7745954/create_script.txt)

**Comment by Sabka** [comment]
@yonkel  tak som vygenerovala tie krajiny aj s kodmi a oznaceniami, ci je aktivna, integruj to prosim do tvojho generate scriptu

[finalCountries.txt](https://github.com/TIS2021-FMFI/zaujem-o-sport/files/7746222/finalCountries.txt)

**Comment by Sabka** [comment]
Tak este jeden update create scriptu premenovanie succes->value na order

[create_script.txt](https://github.com/TIS2021-FMFI/zaujem-o-sport/files/7746286/create_script.txt)

**Comment by Sabka** [comment]
v success su tiez nejake anomalie

![image](https://user-images.githubusercontent.com/26357169/146792366-599fa949-a533-4a57-9e78-93f4beb9d170.png)

ked sa pozriete na tie vysvietene riadky tak z nejakeho neznameho dovodu k nim je v textaku velmi dlhe desatinne cislo... asi by bolo fajn zachovat tie cisla v tvare akom sme ich dostali, aby nam nevznikali numericke chyby pri vypoctoch (@yonkel  pregeneruj to prosim ta s nejakym zaokruhlovanim, lebo sa to deje na viacerych miestach)

**Comment by Sabka** [comment]
co sa tyka branch, tak tak ako som vysvetlila na calle s Richardom, treba im zmenit kody... ak by si nevedel ako, napis mi a vysvetlim znova :)

**Comment by Sabka** [comment]
ten insert do users asi konzultuj s @Ashen-MG  lebo ako password tam treba davat nejako zahashovany string a nie plain text

**Comment by Ashen-MG** [comment]
@yonkel Pre tabuľku users v create scripte:
`password varchar(320)` <- dĺžka bude locknutá pre každý hash na 320 charakteroch (salt+hash)
`type` môže mať integritné obmedzenie CHECK (type = 'admin' or type = 'secretary')
teda vo výsledku:
<pre>
CREATE TABLE users
  (
     id                SERIAL PRIMARY KEY,
     login             VARCHAR UNIQUE,
     password          VARCHAR(320),
     type              VARCHAR
     CHECK (type = 'admin' or type = 'secretary')
  );
</pre>
Môžeme zatiaľ vytvoriť jedného testovacieho admina a jednu sekretárku a potom samozrejme pridáme produkčné.
Môžeš použiť hashe hesiel (9b1ucrgk3lha7fviin652dlshkklv3xk, xlg3yj1tlkf2d902dp80dgg1v5gqpaa6):

c7656114487fd2aa9b04a8e84a0990290b7cfe5102fc68d7ab385e3893dce0736db4ade885158aa04b8da66931af132f38b7eba714941367452cd8c6f8c9d94333813aa694970907ee5b13d8a149e3e280057154b1bca10c08cac1becdd415691afa3eca8a7851985a148bb9268f0f4a3d54a0ef50d493479faa239ec1ac916c2fc2bac252515779ffca59f2a6cebef8bd2328deaaedb052ee2d854b901ac909

cffb56d78ec5b2b57ae2fa2813f8737cf5503597c855c02ea1839112a4a2a9b63eec7f332a486080ff7814242a0d0c76c67a450819ea521d46817a476c8aefe2b08a560316d6c4ba9a89ccaa72cae95d45e80f3245a0bd275ee7e599d22fd3db6a69dc18fa997fd8119466f9068bae8a3f69deb68024239442ddd3a0c6c7452a29dcd67c3a030c0c9057a3bf3ba0ad420163b3ca9f892d6d8f2a2583bdbe49a4

**Comment by yonkel** [comment]
[gen.zip](https://github.com/TIS2021-FMFI/zaujem-o-sport/files/7748776/gen.zip)
[gen_script.txt](https://github.com/TIS2021-FMFI/zaujem-o-sport/files/7748777/gen_script.txt)
[pepe](https://user-images.githubusercontent.com/79480591/146852777-fa5e7457-b74f-42e5-8b61-6d56611475c6.jpg)

to review:
- branch code
- prepojenost ( zaokruhluje na 2 desatinne ) , 0 hodnoty nezapisujem 
- hash nahradeny
- velke cisla su pri relative funding - to mi nenapadlo, to sa chcem spytat Richarda ze ako sa to pocita zatial to je aktualny fund/celkovy fund a tie cisla su strasne male preto to nema vyznam zaokruhlovat

ak mi nieco napadne este updatnem

**Comment by yonkel** [comment]
[create_script.txt](https://github.com/TIS2021-FMFI/zaujem-o-sport/files/7759416/create_script.txt)
[gen_script.txt](https://github.com/TIS2021-FMFI/zaujem-o-sport/files/7759417/gen_script.txt)
[create+gen.txt](https://github.com/TIS2021-FMFI/zaujem-o-sport/files/7759426/create%2Bgen.txt)
[generator.zip](https://github.com/TIS2021-FMFI/zaujem-o-sport/files/7759419/generator.zip)



- dal som dokopy create + gen
- create je upraveny podla poziadaviek 
- generate dalsie bugs co som nasiel --> odstranene 

- zbieha 💯

**Comment by yonkel** [comment]
- pridat  v gen flag active
- zmenit nazvy krajin
