### ISSUE TITLE
Vyber technologii

### ISSUE THREAD

**Issue by Sabka** [TIS2021-FMFI/zaujem-o-sport#3]

**Comment by Ashen-MG** [comment]
Uzatváram, keďže sme sa už dohodli, aké tech. použijeme:
Frontend:
Typescript, react, redux, router, bootstrap 5

Backend:
python, numpy, flask, pandas

DB:
postgresql

Map:
https://blog.bitsrc.io/top-5-map-libraries-for-react-in-2021-20a37ff5234
