### ISSUE TITLE
Vyber sposobu vyuzivania DB

### ISSUE THREAD

**Issue by Sabka** [TIS2021-FMFI/zaujem-o-sport#4]

**Comment by Sabka** [comment]
Myslim, ze na tomto sme sa nejako zhodli, ze bude len basic datove ulozisko a vypocty robime na backende.

Ak suhlasite, tak uzavrite tuto issue.

**Comment by Ashen-MG** [comment]
Uzatváram, tak ako je zobrazené na našom sekvenčnom diagrame - dáta z databázy budú voliteľne spracovávané i.e. pre nejaký use case môže stačiť vytiahnuť raw dáta z databázy a poslať ich ako json naspäť, zatiaľ, čo pri iných sa nad dátami z db ešte urobí nejaký processing/výpočty/...
