### ISSUE TITLE
lokálne DB a DB knižnica

### ISSUE THREAD

**Issue by Sabka** [TIS2021-FMFI/zaujem-o-sport#50]
ahojte, postujem sem nejaké užitočné info k rozbehávaniu lokálnej db a knižnici na prístup do DB pre python.

- budeme používať postgres13, ja som na ubuntu použila tento návod https://linuxiac.com/install-postgresql-on-ubuntu/, asi si skuste najst podobny windowsovy

- ja pouzivam pgAdmin4, aj ten si treba nainstalovat

- moja db sa vola postgres, a user je admin s heslom admin, @Ashen-MG chceme toto zjednocovať ?

Dokumentácia k psycopg2
* https://www.psycopg.org/docs/usage.html#passing-parameters-to-sql-queries
* na zaciatku su uzitocne priklady
* mne osobne na connect nefungoval tento ich sposob, ale potrebovala som zadat explicitne localhost a heslo takto :

> conn = psycopg2.connect(
>     host="localhost",
>     database="postgres",
>     user="admin",
>     password="admin")

Prosím, vyjadrite sa sem ked sa vam podari nainstalovat db aj kniznicu a spustit tie basic prikazy... a posledny zavrite issue :)

**Comment by Ashen-MG** [comment]
Ahojte,
@Sabka Databázové údaje netreba zjednocovať, pretože ich bez tak nebudeme mať v kóde pre bad practice. Miesto toho asi najrozumnejšie to bude čítať z env premenných i.e.:
backend:
from os import environ as env
conn = psycopg2.connect(
     host=env.get("DB_HOST"),
     database=env.get("DB_NAME"),
     user=env.get("DB_USER"),
     password=env.get("DB_PASSWORD")
)

pričom env premenné si viete nastaviť v príkazovom riadku e.g.:
SET DB_NAME=sport
na windowse (otestovať to môžete potom s príkazom echo %DB_NAME% - vypísať by sa mala hodnota sport),
export DB_NAME=sport
na linuxe (opäť otestovať sa to dá s príkazom echo $DB_NAME)

Každopádne knižnicu aj postgresql mám už u seba sprovoznenú, keďže robím kostru pre ten login už aj v rámci db spojenia.

@yonkel @misovsky3 Dajte vedieť čím skôr keby niečo nefunguje :)
