### ISSUE TITLE
doplnenie dat + tabuliek o success, najdene nezrovnalosti

### ISSUE THREAD

**Issue by Sabka** [TIS2021-FMFI/zaujem-o-sport#74]
zistila som, ze len z dat ktore ukladame sa NEDA vypocitat 
- pocet statov v rebricku
- max points v sporte
- celkove body
- minimalne poradie

riesenie je asi take, ze na kazde doplnime tabulku, do ktorej bude treba doparsovat data z Richardovych sheetov...

**Comment by Sabka** [comment]
https://docs.google.com/spreadsheets/d/1kJMzFTdp6kDByo1MMjd6Pv0dlCK6IOC79OYuwicoyEw/edit#gid=1695196393

v zahranicnom financovanie nie je sparsovany posledny riadok combi -> riadok 392 AUTOMOBILE/MOTORCYCLE @yonkel  - **hotove**

- po dogenerovani, check print(c.total_country_funding(160))  -> 9 334 475 000 - **funguje**
- pri Chorvatsku tiez chyba AUTOMOBILE/MOTORCYCLE  a este aj "financovanie inych sportov"
- dansko - automobile - **spravne**
- rucne som presla krajiny po id 108, toto su veci co tam boli cudne
-

**Comment by Sabka** [comment]
do celkoveho financovanie krajiny sa zapocitava aj financovanie "inych sportov"
riadok 488

https://docs.google.com/spreadsheets/d/1kJMzFTdp6kDByo1MMjd6Pv0dlCK6IOC79OYuwicoyEw/edit#gid=1695196393

toto ale zatial nijako nereprezentujeme v DB, na druhej strane, vo vypoctoch nie je uvedene, ze by sme s tym mali pocitat, treba zistit ako to mysli RK

**Comment by yonkel** [comment]
- Iné športy je len podmnozina sportov v tabulke, priamo v riadku "Iné športy" je len sucet vsetkych inych sportov u mna =SUM(H399:H490)
- AUTOMOBILE/MOTORCYCLE - moja chyba ked som menil tabulku tak som zabudol zmenit pri parsovanie range, opravene
- total funding 106 ( Novy zeland ) je dobre podla uvedenych cisiel 
- pocet statov v rebricku a max points v sporte viem ulozit napriklad pod sport z sheetu  "Poradie - sporty", ale celkove body a minimalne poradie ( = pocet statov ? alebo pocet bodov posledneho )  neviem najst 

pre istotu pripajam aj moj upraveny doc z ktoreho cerpam
[Zahranicny_zaujem_sport_2021.xlsx](https://github.com/TIS2021-FMFI/zaujem-o-sport/files/7936708/Zahranicny_zaujem_sport_2021.xlsx)

**Comment by yonkel** [comment]
skusim zhrnut vacsinu zmien ktore som doteraz upravil v mojich tabulkach :

niektore udaje som menil tak aby sedeli v db, najviac zmien bolo pri parametroch, vacsina je tam vypisana

pri financovani zopar cisiel bolo v zlom formate, tak som ich upravil

naposledy som menil BSG a to tak ze podla Kód športu ( co je v tabulkach ) je BOWLING s kodom 15 a taktiez 53, kde 15 obsahuje len branch bowling, 53 petang a ine tak som mu pozmenil nazov na alternative bowling lebo maju aj ine financovanie

podla toho som pozmenil aj BSG
Kód športu |  Sport name |  Názov športu
15 | BOWLING | Bowling 
53 | ALTERNATIVE BOWLING |  Petang

podobny proces aj pre RUGBY / RUGBY UNION / RUGBY LEAGUE
( vlavo moje, vpravo original ) 
![image](https://user-images.githubusercontent.com/79480591/151067555-b9d4e550-c5da-4e10-9d83-d8a6d027e37f.png)

**Comment by Sabka** [comment]
ahoj @yonkel 

ach, tie data su take srandovne... 

Počet krajín v rebríčku krajín v športe = pocet statov v rebricku je v poradie-sporty v riadku 3

max body v sporte =  pocet bodov prveho je v poradie-sporty v riadku 4

Celkový počet bodov krajiny vo všetkých športoch dokopy **podla mna nie je nikde v richardovych datach** takze asi by to bolo dobre zratat ako sucet kazdeho riadka v body-sporty, cize teoreticky toto nemusi mat samostatnu tabulku

Najvyššie umiestnenie krajiny vo svetovom rebríčku cez všetky športy = minimalne poradie krajiny je v poradie-sporty stlpec DK

podla mna by bolo najjednoduchsie vyrobit nove tabulky v style

**Počet krajín v rebríčku krajín v športe**
ID_SPORT | POCET_KRAJIN

**max body v sporte**
ID_SPORT | POCET_BODOV_PRVEHO

**Celkový počet bodov krajiny**
ID_KRAJINY | SUMA_BODOV

**Najvyššie umiestnenie krajiny**
ID_KRAJINY | MIN_UMIESTNENIE

**Comment by Sabka** [comment]
toto mi pride ako najjednoduchsie riesenie, aby sme to nemuseli nasilu pchat do uz existujucich tabuliek, co by bolo matuce

**Comment by Sabka** [comment]
@yonkel vyrobila som branch  db-add-tables v ktorej som vyrobila dane tabulky

mozes v nej pokracovat s generovanim dat
