### ISSUE TITLE
Scenár: Definovanie nového kombinovaného športu

### ISSUE THREAD

**Issue by Ashen-MG** [TIS2021-FMFI/zaujem-o-sport#8]
Každý si skúsi následujúci scenár, či nie je v spore s tým návrhom, ktorý sme navrhli v jamboarde.
Link na prebiehajúci návrh ERD (jamboard):
https://jamboard.google.com/d/1z5ZEr1Tvm9datcRVMrMJQWSZ6K-MBJd3mYDsaaWl2MM/

**Comment by Sabka** [comment]
podla mna trivialne funguje... do comb sport pridame novy riadok s nazvom, a listami odkazov na sporty a koeficienty + triggers na check foreign keys 


Potom ak chceme na zaklade toho updatovat aj financovanie niektorym statom v minulosti (co asi az tak nedava zmysel, ale mozno to bude treba - spytame sa Richarda) tak vieme pridat do nejakej tabulky Finances riadok so suctom ciadtovych sum jednotlivych sportov tvoriacich kombinovany sport

**Comment by Ashen-MG** [comment]
Priamočiare k nášmu prvotnému návrhu, či už ide o dva samostatné (jednotkové) športy (zrejme by sme ich mohli začať nazývať jednotkový šport, dvojkový, ..., n-tý komb. šport) alebo o nejaké  i-te komb. športy.
