### ISSUE TITLE
Zalohovanie DB

### ISSUE THREAD

**Issue by Sabka** [TIS2021-FMFI/zaujem-o-sport#84]

**Comment by Ashen-MG** [comment]
Vymyslieť:
Ako sa bude k zálohovaným súborom pristupovať.
Zavolanie linuxového príkazu na vytvorenie zálohy pred nahratím dát na každom mieste (zrejme s os.system)

Príkazy:
Vytvorenie zálohy e.g.:
pg_dump "host=localhost port=5432 dbname=sport user=postgres" > sport_db_backup.bak

Na vytvorenie databázy zo zálohy:
dropdb -U postgres sport
createdb -U postgres sport
psql -U postgres sport < sport_db_backup.bak
