### ISSUE TITLE
Potrebné databázové funkcie

### ISSUE THREAD

**Issue by Ashen-MG** [TIS2021-FMFI/zaujem-o-sport#87]
vrátenie nového kódu (neexistujúceho) športu
vrátenie nového kódu (neexistujúceho) branchu
vrátenie nového kódu (neexistujúceho) combi branchu (podľa toho či bude checknuté 'kombinované' sa zobrazí daný kód)

**Comment by Sabka** [comment]
toto je myslene ako tie navrhy na nove kody, vsak ?

**Comment by Ashen-MG** [comment]
@Sabka hej

**Comment by Sabka** [comment]
@Ashen-MG  mas PR do tvojej branche kde su tie funkcie
