### ISSUE TITLE
Scenár: Rozdelenie kombinovaného športu na jednotlivé športy

### ISSUE THREAD

**Issue by Ashen-MG** [TIS2021-FMFI/zaujem-o-sport#9]
Každý si skúsi následujúci scenár, či nie je v spore s tým návrhom, ktorý sme navrhli v jamboarde.
Link na prebiehajúci návrh ERD (jamboard):
https://jamboard.google.com/d/1z5ZEr1Tvm9datcRVMrMJQWSZ6K-MBJd3mYDsaaWl2MM/

**Comment by Sabka** [comment]
tu je potreba si uvedomit, ze co vlastne znamena jednoduchy (t.j nekombinovany sport), ze je to vlastne kombinovany sport s 1 odkazom na sport a 1 odkazom na koeficient kory je navyse 1.

Co je ale dalsia vec, na kombinovany sport sa viaze tabulka (aspon v mojej predstave) ktora storuje udaje zo zdroja jedna, nech sa pre jednoduchost vola financies a ta sa viaze na komb. sport.

Cize co sa pri takom deleni stane ? 
- podla mna treba pre kazdy vzniknuty sport vytvorit jeho zrkadlo v tabulke komb. sport (ak este neexistuje) a vo finances vytvorit n riadkov s podielom penazi od danej krajiny. Stare data zmazat.

To by v tomto navrhu malo ist celkom vpohode

**Comment by Ashen-MG** [comment]
Dané operácie si viem predstaviť naprogramované ako v SQL, tak po častiach s pomocou backendu (zrejme prehladnejšia voľba). Za predpokladu, že rozdelenie komb. športu vnímame ako vytváranie 'nových' jednotlivých športov je podľa mňa náš návrh stále vzdorný.
@Sabka Určite preberme na našom stretnutí tvoje uvažovanie nad viazanou tabuľkou pre komb. šport - mám tam nejaké otázky / diery.
