### ISSUE TITLE
zjednotit rovnake meny v generate scripte

### ISSUE THREAD

**Issue by Sabka** [TIS2021-FMFI/zaujem-o-sport#90]

**Comment by Sabka** [comment]
este by bolo okay vymazat cely stlpec relative_funding v tabulke funding... nikde sa totiz nevyuzije

**Comment by yonkel** [comment]
zjednotene podla [ISO 4217 ](https://en.wikipedia.org/wiki/ISO_4217)
relative_funding vymazany

pull request #96
