### ISSUE TITLE
Potrebné db funckie

### ISSUE THREAD

**Issue by Ashen-MG** [TIS2021-FMFI/zaujem-o-sport#91]
addCombiBranch() - súvisí s 3.2.2.5 (check kombinované)

Ak správne chápem mimo zákl.: sportCode, sportName, combiBranchCode, combiBranchName, country
je potrebné odvetvia, z ktorých sa dané kombinované odvetvie skladá pridávať po `id`+koeficient, pričom id je `id` je stĺpec z tabuľky branch (`code` mi nedával zmysel v tomto prípade).

**Comment by Sabka** [comment]
ahoj, no ked som sa nad tymto zamyslela, bude to zrejme vacsi problem nez sa zda...
lebo code pre branch nie je jednoznacny identifikator, zaroven ale chceme pre uzivatelov robit abstrakciu od idcok, ktore su ....


jednoznacny identifikator branch je **sportCode.branchCode** co je ale pomerne divne kedze kombi branch sa neviaze k sportu (aj ked, subbranche sa viazu k sportu) takze jo, asi to treba prerobit tak, ze subbranch sa bude zadavat pomocou sportcode + branchcode

Dava ti to zmysel?

**Comment by Ashen-MG** [comment]
@Sabka hej aj nad tým som premýšlal - uvidím, čo bude teda z UI pohľadu najlepšie/najrýchlejšie

**Comment by Ashen-MG** [comment]
Ešte bude potrebná:
getSports() ktorá vracia športy (title, code), ale iba také, ktoré majú zmysel (ako sme sa včera bavili, ak majú branch)

**Comment by Sabka** [comment]
vsetky branche so sportami -> getBranchesWithSports() na fronte, ako sme sa dohodli potom urob nejake zobrazovanie v zmysle **1.2 ATHLETICS-Sprint**


getSportsWithExisitingBranch() -> vrati naozaj len tie sporty, kde existuje pre ne nejaky branch

**Comment by Sabka** [comment]
vsetky branche so sportami -> getBranchesWithSports() na fronte, ako sme sa dohodli potom urob nejake zobrazovanie v zmysle **1.2 ATHLETICS-Sprint**


getSportsWithExisitingBranch() -> vrati naozaj len tie sporty, kde existuje pre ne nejaky branch

**Comment by Ashen-MG** [comment]
@Sabka Ešte chýba addCombiBranch()
Prosím, daj vstupy z frontendu ako parametre funkcie.

**Comment by Sabka** [comment]
@Ashen-MG  asi si zjednotme predstavu o parametroch...

moja predstava:
parametre teda budu :
- novy kod
- nove meno
- is combined = true
- krajina
- dict o subbranch, kde kluc je kod sportu a obsahuje ako value dict, v ktorom su kluce branche a hodnoty tie percentualne hodnoty , cize nieco v zmysle d[sport][branch] = 0.1

alebo aky format by ti viacej vyhovoval ?

**Comment by Ashen-MG** [comment]
branchCode, branchTitle, isCombined=true, countryCode sedí.
Subbranche by mi bolo jednoduchšie (kvôli spôsobu aktualizovania statu) robiť ako list máp i.e.
[{sportCode1: ..., branchCode1: ..., coefficient: ...}, ...]
Sedelo by ti to aj takto? @Sabka

**Comment by Sabka** [comment]
@Ashen-MG  jo, uplne vpoho... vdaka ze sme si to zjednotili

**Comment by Sabka** [comment]
@Ashen-MG robim to teda tak ako si napisal, ze nazvy su CamelCase
